module.exports = {
  REQUIRED: 'REQUIRED',
  MIN: 'MIN',
  MAX: 'MAX',
  MIN_LENGTH: 'MIN_LENGTH',
  MAX_LENGTH: 'MAX_LENGTH',
  IS_EMAIL: 'IS_EMAIL',
  IS_NUMBER: 'IS_NUMBER',
  IS_EQUAL: 'IS_EQUAL',
  IS_URL: 'IS_URL',
  IS_ALPHA: 'IS_ALPHA',
  IS_BOOLEAN: 'IS_BOOLEAN',
  IS_MEMBER: 'IS_MEMBER',
  IS_OBJECT_ID: 'IS_OBJECT_ID',
  IS_ARRAY: 'IS_ARRAY',
  IS_MOBILE: 'IS_MOBILE',
  IS_DATE: 'IS_DATE',
  NO_SPACE: 'NO_SPACE'
};
